name: funminton_club_app
description: "배드민턴 클럽 관리 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  open_filex: ^4.7.0
  downloadsfolder: ^1.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.0

  image_picker: ^1.0.0
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/excel/
